		>>SOURCE FORMAT FREE
IDENTIFICATION DIVISION.
PROGRAM-ID. testguicob.

ENVIRONMENT DIVISION.
CONFIGURATION SECTION.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 result		   	USAGE BINARY-LONG.
01 gtk-window          USAGE POINTER.
01 gtk-box             USAGE POINTER.
01 gtk-hello	       USAGE POINTER.
01 gtk-textentry       USAGE POINTER.
01 gtk-goodbye         USAGE POINTER.

01 callback				USAGE PROCEDURE-POINTER.
01 params				USAGE POINTER.

PROCEDURE DIVISION.
CALL "CBL_OC_GTK_INIT_CHECK" RETURNING result END-CALL
	DISPLAY "init: " result END-DISPLAY

CALL "CBL_OC_GTK_WINDOW_NEW" RETURNING gtk-window END-CALL
	DISPLAY "win: " gtk-window END-DISPLAY

CALL "CBL_OC_GTK_WINDOW_SET_TITLE"
	USING BY VALUE gtk-window
		BY REFERENCE "GnuCOBOL GTK+"
END-CALL
	DISPLAY "Title: " gtk-window END-DISPLAY

CALL "CBL_OC_GTK_CONTAINER_SET_BORDER_WIDTH"
	USING BY VALUE gtk-window
		BY VALUE 5
END-CALL
	DISPLAY "border: " gtk-window END-DISPLAY

SET callback TO ENTRY "CBL_OC_destroy"
CALL "CBL_OC_G_SIGNAL_CONNECT"
	USING BY VALUE gtk-window
		BY REFERENCE "delete_event" & x"00"
		BY VALUE callback
		by VALUE params
END-CALL
CALL "CBL_OC_GTK_VBOX_NEW"
	USING BY VALUE 0
		by VALUE 5
	RETURNING gtk-box
END-CALL
	DISPLAY "box: " gtk-box END-DISPLAY
	
CALL "CBL_OC_GTK_CONTAINER_ADD"
	USING BY VALUE gtk-window
		by VALUE gtk-box
END-CALL

CALL "CBL_OC_GTK_BUTTON_NEW_WITH_LABEL"
	USING BY REFERENCE "Hello from GnuCOBOL and GTK" & x"00"
	RETURNING gtk-hello
END-CALL
	DISPLAY "button " gtk-hello END-DISPLAY

SET callback TO ENTRY "CBL_OC_hello"

CALL "CBL_OC_G_SIGNAL_CONNECT"
	USING BY VALUE gtk-hello
	BY REFERENCE "clicked" & x"00"
	BY VALUE callback
	BY VALUE params
END-CALL

CALL "CBL_OC_GTK_BOX_PACK_START"
	USING BY VALUE gtk-box
		BY VALUE gtk-hello
		BY VALUE 1
		BY VALUE 1
		BY VALUE 0
END-CALL

CALL "CBL_OC_GTK_WIDGET_SHOW"
	USING BY VALUE gtk-hello
END-CALL

CALL "CBL_OC_GTK_ENTRY_NEW"
	RETURNING gtk-textentry
END-CALL

SET callback TO ENTRY "CBL_OC_activate"
CALL "CBL_OC_G_SIGNAL_CONNECT"
	USING BY VALUE gtk-textentry
		BY REFERENCE "activate" & x"00"
		BY VALUE callback
		BY VALUE gtk-textentry
END-CALL

CALL "CBL_OC_GTK_BOX_PACK_START"
	USING BY VALUE gtk-box
		BY VALUE gtk-textentry
		BY VALUE 1
		BY VALUE 1
		BY VALUE 0
END-CALL

CALL "CBL_OC_GTK_WIDGET_SHOW"
	USING BY VALUE gtk-textentry
END-CALL

CALL "CBL_OC_GTK_BUTTON_NEW_WITH_LABEL"
	USING BY REFERENCE "Goodbye from GnuCOBOL and GTK" & x"00"
		RETURNING gtk-goodbye
END-CALL
	DISPLAY "button: " gtk-goodbye END-DISPLAY
	
SET callback TO ENTRY "CBL_OC_destroy"
CALL "CBL_OC_G_SIGNAL_CONNECT"
	USING BY VALUE gtk-goodbye
		BY REFERENCE "clicked" & x"00"
		BY VALUE callback
		BY VALUE params
END-CALL

CALL "CBL_OC_GTK_BOX_PACK_START"
	USING BY VALUE gtk-box
		BY VALUE gtk-goodbye
		BY VALUE 1
		BY VALUE 1
		BY VALUE 0
END-CALL
	DISPLAY "pack: " gtk-box END-DISPLAY

CALL "CBL_OC_GTK_WIDGET_SHOW"
	USING BY VALUE gtk-goodbye
END-CALL
	
CALL "CBL_OC_GTK_WIDGET_SHOW"
	USING BY VALUE gtk-box
END-CALL

CALL "CBL_OC_GTK_WIDGET_SHOW"
	USING BY VALUE gtk-window
END-CALL

CALL "CBL_OC_GTK_MAIN" END-CALL

DISPLAY "ending..." END-DISPLAY

GOBACK.
END PROGRAM testguicob.
